type WeatherCategory = "clear" | "cloudy" | "rain" | "snow" | "storm";
type TimeOfDay = "morning" | "afternoon" | "evening" | "night";
type BackgroundKey = `${WeatherCategory}-${TimeOfDay}`;

// Generated by scripts/cover-generator/generate.js. Do not edit manually.
export const availableVariantsBySet: Record<
  string,
  Partial<Record<BackgroundKey, number[]>>
> = {
  "jack-russell": {
    "clear-afternoon": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "clear-evening": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ],
    "clear-morning": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ],
    "clear-night": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      12
    ],
    "cloudy-afternoon": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ],
    "cloudy-evening": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ],
    "cloudy-morning": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      12
    ],
    "cloudy-night": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      12
    ],
    "rain-afternoon": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      9
    ],
    "rain-evening": [
      1,
      2,
      3,
      4,
      5,
      6,
      8
    ],
    "rain-morning": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      10
    ],
    "rain-night": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      11
    ],
    "snow-afternoon": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "snow-evening": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      10,
      11
    ],
    "snow-morning": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      10
    ],
    "snow-night": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      11
    ],
    "storm-afternoon": [
      1,
      2,
      3,
      5,
      6,
      7,
      8,
      9,
      11
    ],
    "storm-evening": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "storm-morning": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ],
    "storm-night": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      11
    ]
  },
  "samurai-zen": {
    "clear-afternoon": [
      1,
      2,
      3,
      4
    ],
    "clear-evening": [
      1,
      2,
      3,
      4
    ],
    "clear-morning": [
      1,
      2,
      3,
      4
    ],
    "clear-night": [
      1,
      2,
      3,
      4
    ],
    "cloudy-afternoon": [
      1,
      2,
      3,
      4
    ],
    "cloudy-evening": [
      1,
      2,
      3,
      4
    ],
    "cloudy-morning": [
      1,
      2,
      3,
      4
    ],
    "cloudy-night": [
      1,
      2,
      3,
      4
    ],
    "rain-afternoon": [
      1,
      2,
      3,
      4
    ],
    "rain-evening": [
      1,
      2,
      3,
      4
    ],
    "rain-morning": [
      1,
      2,
      3,
      4
    ],
    "rain-night": [
      1,
      2
    ],
    "snow-afternoon": [
      1,
      2,
      3,
      4
    ],
    "snow-evening": [
      1,
      2,
      3,
      4
    ],
    "snow-morning": [
      1,
      2,
      3,
      4
    ],
    "storm-afternoon": [
      1,
      2,
      3,
      4
    ],
    "storm-evening": [
      1,
      2,
      3,
      4
    ],
    "storm-morning": [
      1,
      2,
      3,
      4
    ]
  },
  "nothing-os": {
    "clear-afternoon": [
      2,
      3
    ],
    "clear-evening": [
      1,
      3,
      4
    ],
    "clear-morning": [
      2,
      4
    ],
    "cloudy-afternoon": [
      1,
      3,
      4
    ],
    "cloudy-evening": [
      1,
      2
    ],
    "cloudy-morning": [
      1,
      2,
      3,
      4
    ],
    "rain-afternoon": [
      2,
      3,
      4
    ],
    "rain-evening": [
      1,
      4
    ],
    "rain-morning": [
      1,
      2
    ],
    "snow-afternoon": [
      1,
      2,
      3,
      4
    ],
    "snow-evening": [
      1,
      2,
      3
    ],
    "snow-morning": [
      1,
      3,
      4
    ],
    "storm-afternoon": [
      3,
      4
    ],
    "storm-evening": [
      1,
      2,
      3
    ],
    "storm-morning": [
      1
    ]
  },
  "arcade-fighter": {},
  "pocket-clay": {},
  "nordic-paper": {}
};
